# Generated by Django 4.2.2 on 2023-06-09 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='subtitulo',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 15, 22, 56, 223994)),
        ),
    ]
